### ISSUE TITLE
[TODO] Study api 추가

### ISSUE THREAD

**Issue by lijm1358** [PNU-AID/AID_Backend_v2#22]
### 추가 기능 설명

스터디 관련 api 제작

* [x] 스터디 생성
* [x] 스터디 조회, 상세 조회
* [x] 스터디 삭제
* [x] 스터디 업데이트
* [x] 스터디 참가
* [x] 스터디 참가 신청 승인
* ~~스터디 좋아요~~
* [x] 스터디 나가기
* [x] 스터디 owner 변경
