### ISSUE TITLE
[TODO] User API 작성

### ISSUE THREAD

**Issue by sihyeong671** [PNU-AID/AID_Backend_v2#24]
## TODOs
- [x] User CRUD 추가
- [x] User API Permission 조정
- [x] Token 인증 추가
- [x] 로그아웃 추가
- [ ] 회원 탈퇴 작동 확인
- [ ] 프론트 위한 docs 추가 작성
